import os
import json
import glob
from .base import BaseGenerator

class JekyllGenerator(BaseGenerator):
    """Transforms raw markdown into Jekyll layout wrapped pages."""

    def __init__(self, dst, **kwargs):
        super().__init__(**kwargs)
        self.input_folder = "docs"
        self.obj_schema_path = "schemas/arena-schema-files.json"
        self.output_folder = dst

    def build(self):
        print(f"Generating Jekyll site from {self.input_folder}/ to {self.output_folder}/")
        if not os.path.isdir(self.output_folder):
            os.makedirs(self.output_folder)

        for oldpath in glob.iglob(os.path.join(self.output_folder, "*.md")):
            os.remove(oldpath)

        sec_title = "ARENA Objects"
        sec_sub_title = "Objects Schema"

        md_lines = [
            "---\n",
            f"title: {sec_sub_title}\n",
            "layout: default\n",
            f"parent: {sec_title}\n",
            "has_children: true\n",
            "has_toc: false\n",
            "---\n",
            "\n<!--CAUTION: This file is autogenerated from https://github.com/arenaxr/arena-schemas. Changes made here may be overwritten.-->\n\n",
            "# ARENA Message Objects\n\n",
            "|Object Message|Description|\n",
            "| :--- | :--- |\n"
        ]

        if os.path.exists(self.obj_schema_path):
            with open(self.obj_schema_path, "r") as json_file_all:
                files = json.load(json_file_all)
            for file in files:
                filename = os.path.basename(files[file]["file"])
                title = files[file]["title"]
                desc = files[file]["description"]
                md_lines.append(f"|[{title}]({filename[:-5]})|{desc}|\n")
        else:
            print(f"Warning: {self.obj_schema_path} missing.")

        out = "".join(md_lines)
        index_path = os.path.join(self.output_folder, "index.md")
        print(f"->{index_path}")
        with open(index_path, "w") as f:
            f.write(out)

        for filename in sorted(os.listdir(self.input_folder)):
            if not filename.endswith(".md"):
                continue
            with open(os.path.join(self.input_folder, filename), "r") as f:
                text = f.read()

            lines = text.split("\n")
            if len(lines) > 1 and lines[1].startswith("`"):
                title_val = lines[1].strip("`")
            else:
                title_val = "Untitled"

            md_lines = [
                "---\n",
                f"title: {title_val}\n",
                "layout: default\n",
                f"parent: {sec_sub_title}\n",
                f"grand_parent: {sec_title}\n",
                "---\n",
                "\n<!--CAUTION: This file is autogenerated from https://github.com/arenaxr/arena-schemas. Changes made here may be overwritten.-->\n\n",
                text
            ]

            out = "".join(md_lines)
            md_path = os.path.join(self.output_folder, filename)
            print(f"->{md_path}")
            with open(md_path, "w") as f:
                f.write(out)
